version: '2'

services:
  traefik:
    image: traefik:latest
    command: --web --docker --logLevel=INFO
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml:ro
      - ./acme.json:/acme.json
    container_name: traefik
    labels:
      - "traefik.frontend.rule=Host:mon.ioterr.se"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic=admin:$$apr1$$IBj9Hfsd$$kf7vXLpY4/9XD365jcp/n1"
networks:
  reverse-proxy:
    external: true

